language: python
sudo: false
install:
  - pip install tox
script:
  - tox
# for python 3.5 and 3.6, see https://github.com/travis-ci/travis-ci/issues/4794
# for python 3.7, see https://github.com/travis-ci/travis-ci/issues/9815
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36-2.0
    - python: 3.7
      env: TOXENV=py37-2.0
      dist: xenial
      sudo: true
    - python: 3.6
      env: TOXENV=py36-2.1
    - python: 3.7
      env: TOXENV=py37-2.1
      dist: xenial
      sudo: true
