# Generated by Django 2.1.7 on 2019-03-06 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAuthnUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.BinaryField(blank=True, null=True)),
                ('credential_public_key', models.BinaryField(blank=True, null=True)),
                ('registration_challenge', models.BinaryField(blank=True, null=True)),
                ('authentication_challenge', models.BinaryField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
